export const WS_MESSAGE_TYPES = {
  AUTH: "AUTH",
  AUTH_SUCCESS: "AUTH_SUCCESS",
  SUBMIT_ANSWER: "SUBMIT_ANSWER",
  START_GAME: "START_GAME",
  JOIN_ROOM: "JOIN_ROOM",
  CREATE_ROOM: "CREATE_ROOM",
  UPDATE_ROOM_SETTINGS: "UPDATE_ROOM_SETTINGS",
  KICK_USER: "KICK_USER",
  LEAVE_ROOM: "LEAVE_ROOM",

  STOP_GAME: "STOP_GAME",
  RESTART_GAME: "RESTART_GAME",
  HEARTBEAT_RESPONSE: "HEARTBEAT_RESPONSE",
  JOIN_ROOM_SUCCESS: "JOIN_ROOM_SUCCESS",
  CREATE_ROOM_SUCCESS: "CREATE_ROOM_SUCCESS",
  USER_JOINED: "USER_JOINED",
  USER_LEFT: "USER_LEFT",
  USER_KICKED: "USER_KICKED",
  HOST_CHANGED: "HOST_CHANGED",
  KICKED: "KICKED",
  GAME_STARTING: "GAME_STARTING",
  NEW_QUESTION: "NEW_QUESTION",
  ANSWER_SUBMITTED: "ANSWER_SUBMITTED",
  QUESTION_RESULTS: "QUESTION_RESULTS",
  GAME_ENDED: "GAME_ENDED",
  GAME_STOPPED: "GAME_STOPPED",
  GAME_RESTARTED: "GAME_RESTARTED",

  SETTINGS_UPDATED: "SETTINGS_UPDATED",
  ERROR: "ERROR",
  HEARTBEAT: "HEARTBEAT",

} as const;

export type WSMessageType = typeof WS_MESSAGE_TYPES[keyof typeof WS_MESSAGE_TYPES]; 