export const WS_MESSAGE_TYPES = {
  // Client-to-server message types
  AUTH: "AUTH",
  AUTH_SUCCESS: "AUTH_SUCCESS",
  SUBMIT_ANSWER: "SUBMIT_ANSWER",
  START_GAME: "START_GAME",
  JOIN_ROOM: "JOIN_ROOM",
  CREATE_ROOM: "CREATE_ROOM",
  UPDATE_SETTINGS: "UPDATE_SETTINGS",
  KICK_USER: "KICK_USER",
  LEAVE_ROOM: "LEAVE_ROOM",

  PAUSE_GAME: "PAUSE_GAME",
  RESUME_GAME: "RESUME_GAME",
  STOP_GAME: "STOP_GAME",
  HEARTBEAT_RESPONSE: "HEARTBEAT_RESPONSE",
  SKIP_QUESTION: "SKIP_QUESTION",
  REACTION: "REACTION",

  // Server-to-client message types
  JOIN_ROOM_SUCCESS: "JOIN_ROOM_SUCCESS",
  CREATE_ROOM_SUCCESS: "CREATE_ROOM_SUCCESS",
  USER_JOINED: "USER_JOINED",
  USER_LEFT: "USER_LEFT",
  HOST_CHANGED: "HOST_CHANGED",
  KICKED: "KICKED",
  GAME_STARTING: "GAME_STARTING",
  NEW_QUESTION: "NEW_QUESTION",
  ANSWER_SUBMITTED: "ANSWER_SUBMITTED",
  QUESTION_RESULTS: "QUESTION_RESULTS",
  GAME_ENDED: "GAME_ENDED",
  GAME_PAUSED: "GAME_PAUSED",
  GAME_RESUMED: "GAME_RESUMED",
  GAME_STOPPED: "GAME_STOPPED",

  SETTINGS_UPDATED: "SETTINGS_UPDATED",
  ERROR: "ERROR",
  HEARTBEAT: "HEARTBEAT",
  QUESTION_SKIPPED: "QUESTION_SKIPPED",
  USER_REACTION: "USER_REACTION",
} as const;

export type WSMessageType = typeof WS_MESSAGE_TYPES[keyof typeof WS_MESSAGE_TYPES]; 